
name: ci
on:
  push:
    branches: [ quant-init ]
  pull_request:
    branches: [ main ]
jbs:  test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install
      run: |
      python -m venv .venv
      . .venv/bin/activate
      pip install -r sol_